name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    - name: Compile with MSVC
      run: cl /EHsc /std:c++17 /I "C:\C++ Libraries\SFML-3.0.0-windows-vc17-32-bit\SFML-3.0.0\include" main.cpp /link "/LIBPATH:C:\C++ Libraries\SFML-3.0.0-windows-vc17-32-bit\SFML-3.0.0\lib" sfml-graphics.lib sfml-window.lib sfml-system.lib
