name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    - name: Compile with MinGW
      run: g++ -o game.exe main.cpp $(pkg-config --cflags --libs sfml-all)

