name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        bootstrap-vcpkg.bat

    - name: Install SFML and Dependencies via vcpkg
      run: |
        vcpkg install sfml:x64-windows
        vcpkg install openal-soft:x64-windows libvorbis:x64-windows libflac:x64-windows

    - name: Setup MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1.4.1

    - name: Compile C++ Project with MSVC and SFML
      run: cl /EHsc /std:c++17 /I "C:\vcpkg\installed\x64-windows\include" main.cpp /link "/LIBPATH:C:\vcpkg\installed\x64-windows\lib" sfml-graphics.lib sfml-window.lib sfml-system.lib sfml-audio.lib sfml-network.lib

    - name: Verify SFML Installation
      run: dir C:\vcpkg\installed\x64-windows\lib | findstr sfml
